name: .NET Code Formatting Check

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Run dotnet format
        run: dotnet format --check --verbosity detailed
